### ISSUE TITLE
What is the Return type of v ,_ := <-c.Recv

### ISSUE THREAD

**Issue by furusiyya** [hectane/go-nonblockingchan#1]
I have stored `[]string` and on receiving side:
`v ,_ := <-c.Recv`
I checked the type of `v` with `reflect.Type()` and it return `[]string`. Now when I try to access value with `v[0]`, I end up with the following error:
`invalid operation: v[0] (type interface {} does not support indexing)`

**Comment by furusiyya** [comment]
I solve this by implementing `[]string` type assertion. But Still I wonder why I need to apply assertion on already `[]string`
var value []string = v.([]string)

**Comment by nathan-osman** [comment]
In order to work with any type, `NonBlockingChan` must use the generic `interface{}` type for the channel. Since you (as the user of the class) know the type of values being sent, you must then assert the type when you receive the values.

**Comment by furusiyya** [comment]
Thanks :)
